name: morphodynamics
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - pandas
  - scikit-image
  - jupyter
  - jupyterlab
  - ipywidgets
  - pip
  - ipympl
  - python-graphviz
  - pip:
    - cellpose
    - dill
    - bokeh>=0.13.0
    - tqdm
    - tifffile