name: morphodynamics
channels:
  - conda-forge
dependencies:
  - python>3.4,<3.8
  - scipy
  - numpy
#  - mkl=2019.3
  - numba>=0.43.1
  - pyqt
  - matplotlib
  - pandas
  - scikit-image
  - jupyter
  - jupyterlab
  - ipywidgets
  - nodejs
  - pip
  - ipympl
  - python-graphviz
  - dask-jobqueue
  - pip:
    - dill
    - bokeh>=0.13.0
    - mxnet-mkl
    - opencv-python-headless
    - pyqtgraph==0.11.0rc0
    - natsort
    - google-cloud-storage
    - tqdm
    - cellpose
    - .