name: morphodynamics
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - matplotlib
  - pandas
  - scikit-image
  - jupyter
  - jupyterlab
  - ipywidgets
  - nodejs
  - pip
  - nd2reader
  - ipympl
  - pip:
    - dill
    - tifffile
    - aicsimageio