name: morphodynamics
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>3.4,<3.8
  - pytorch
  - scipy
  - numpy
  - numba>=0.43.1
  - pyqt
  - pandas
  - scikit-image
  - jupyter
  - jupyterlab=2.*
  - ipywidgets
  - nodejs
  - pip
  - ipympl
  - python-graphviz
  - pip:
    - dill
    - bokeh>=0.13.0
    - opencv-python-headless
    - pyqtgraph==0.11.0rc0
    - natsort
    - google-cloud-storage
    - tqdm
    - cellpose
    - git+https://github.com/guiwitz/MorphoDynamics.git@master#egg=morphodynamics
    - git+https://github.com/guiwitz/microfilm.git@master#egg=microfilm
    - jedi==0.17.2
    - tifffile