name: morphodynamics
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - mkl=2019.3
  - numba>=0.43.1
  - pyqt
  - matplotlib
  - pandas
  - scikit-image
  - jupyter
  - jupyterlab
  - ipywidgets
  - nodejs
  - pip
  - nd2reader
  - ipympl
  - python-graphviz
  - pip:
    - dill
    - tifffile
    - aicsimageio
    - mxnet-mkl
    - opencv_python
    - pyqtgraph==0.11.0rc0
    - natsort
    - google-cloud-storage
    - tqdm
    - cellpose
    - .
    - "dask[complete]"